"""Executable memory-to-action studies with lazy public exports.

Native sidecars import the wire schema without importing the analysis, provider,
or model stacks. Public ``from harness.memory_trials import ...`` calls retain
the same API and load only the module that owns the requested symbol.
"""

from __future__ import annotations

import importlib

_EXPORTS = {
    "CollectionResult": "harness.memory_trials.collection",
    "collect_resumable": "harness.memory_trials.collection",
    "BGE_POOLING_STRATEGY": "harness.memory_trials.dense_control",
    "BGE_QUERY_INSTRUCTION": "harness.memory_trials.dense_control",
    "DenseBGERetrievalMemorySystem": "harness.memory_trials.dense_control",
    "DenseEmbeddingBatch": "harness.memory_trials.dense_control",
    "DenseEmbeddingIdentity": "harness.memory_trials.dense_control",
    "HTTPDenseEmbeddingClient": "harness.memory_trials.dense_control",
    "InProcessDenseEmbeddingClient": "harness.memory_trials.dense_control",
    "ReplayableMemoryWorld": "harness.memory_trials.engine",
    "AnthropicMessagesCompletion": "harness.memory_trials.frontier_providers",
    "AnthropicMessagesConfig": "harness.memory_trials.frontier_providers",
    "GeminiGenerateContentCompletion": "harness.memory_trials.frontier_providers",
    "GeminiGenerateContentConfig": "harness.memory_trials.frontier_providers",
    "OpenAIResponsesCompletion": "harness.memory_trials.frontier_providers",
    "OpenAIResponsesConfig": "harness.memory_trials.frontier_providers",
    "FrozenMemoryBundleError": "harness.memory_trials.frozen",
    "FrozenMemorySystem": "harness.memory_trials.frozen",
    "task_manifest_sha256": "harness.memory_trials.frozen",
    "FEATURE_NAMES": "harness.memory_trials.learned_control",
    "FORBIDDEN_POLICY_INPUTS": "harness.memory_trials.learned_control",
    "FrozenLearnedControlArtifact": "harness.memory_trials.learned_control",
    "LearnedNextUseMemorySystem": "harness.memory_trials.learned_control",
    "fit_learned_next_use": "harness.memory_trials.learned_control",
    "LONGMEMEVAL_OFFICIAL_PROMPT_PORT_VERSION": "harness.memory_trials.longmemeval_judge",
    "LongMemEvalJudgeCase": "harness.memory_trials.longmemeval_judge",
    "LongMemEvalJudgeContract": "harness.memory_trials.longmemeval_judge",
    "LongMemEvalJudgeError": "harness.memory_trials.longmemeval_judge",
    "LongMemEvalJudgment": "harness.memory_trials.longmemeval_judge",
    "official_answer_check_prompt": "harness.memory_trials.longmemeval_judge",
    "official_judge_request_payload": "harness.memory_trials.longmemeval_judge",
    "parse_official_judgment": "harness.memory_trials.longmemeval_judge",
    "prepare_longmemeval_judge_cases": "harness.memory_trials.longmemeval_judge",
    "seal_judge_case": "harness.memory_trials.longmemeval_judge",
    "seal_official_judge_contract": "harness.memory_trials.longmemeval_judge",
    "seal_judgment": "harness.memory_trials.longmemeval_judge",
    "summarize_longmemeval_judgments": "harness.memory_trials.longmemeval_judge",
    "write_judge_packet": "harness.memory_trials.longmemeval_judge",
    "LIFECYCLE_PROTOCOL_VERSION": "harness.memory_trials.lifecycle",
    "LifecycleCapability": "harness.memory_trials.lifecycle",
    "LifecycleCheckpoint": "harness.memory_trials.lifecycle",
    "LifecycleCommand": "harness.memory_trials.lifecycle",
    "LifecycleEvent": "harness.memory_trials.lifecycle",
    "LifecycleFeedback": "harness.memory_trials.lifecycle",
    "LifecycleMaintenance": "harness.memory_trials.lifecycle",
    "LifecycleOperationReceipt": "harness.memory_trials.lifecycle",
    "LifecyclePhase": "harness.memory_trials.lifecycle",
    "LifecyclePlan": "harness.memory_trials.lifecycle",
    "LifecyclePort": "harness.memory_trials.lifecycle",
    "LifecycleQuery": "harness.memory_trials.lifecycle",
    "LifecycleSystemReceipt": "harness.memory_trials.lifecycle",
    "LifecycleTraceReceipt": "harness.memory_trials.lifecycle",
    "MemoryLifecycleError": "harness.memory_trials.lifecycle",
    "ReferenceLifecyclePort": "harness.memory_trials.lifecycle",
    "SubprocessLifecyclePort": "harness.memory_trials.lifecycle",
    "run_lifecycle_plan": "harness.memory_trials.lifecycle",
    "MemPalaceEquivalenceEvidence": "harness.memory_trials.mempalace_control",
    "MemPalaceRawSessionMemorySystem": "harness.memory_trials.mempalace_control",
    "MemPalaceRetrievalBatch": "harness.memory_trials.mempalace_control",
    "MemPalaceRetrievalPort": "harness.memory_trials.mempalace_control",
    "MemPalaceRuntimeIdentity": "harness.memory_trials.mempalace_control",
    "MemPalaceSessionDocument": "harness.memory_trials.mempalace_control",
    "build_mempalace_session_documents": "harness.memory_trials.mempalace_control",
    "MEMORY_ACTION_JSON_SCHEMA": "harness.memory_trials.models",
    "ActorOutput": "harness.memory_trials.models",
    "CompletionResult": "harness.memory_trials.models",
    "DeterministicMemoryActor": "harness.memory_trials.models",
    "JsonCompletionMemoryActor": "harness.memory_trials.models",
    "memory_action_json_schema": "harness.memory_trials.models",
    "TransformersMemoryActor": "harness.memory_trials.models",
    "OpenAICompatibleCompletion": "harness.memory_trials.openai_compatible",
    "OpenAICompatibleConfig": "harness.memory_trials.openai_compatible",
    "FrozenProceduralBankArtifact": "harness.memory_trials.procedural_bank",
    "FrozenProceduralBankRetriever": "harness.memory_trials.procedural_bank",
    "ProceduralBankItem": "harness.memory_trials.procedural_bank",
    "ProceduralBankItemInput": "harness.memory_trials.procedural_bank",
    "ProceduralHit": "harness.memory_trials.procedural_bank",
    "ProceduralQuery": "harness.memory_trials.procedural_bank",
    "ProceduralRetrieval": "harness.memory_trials.procedural_bank",
    "ProceduralSplitManifest": "harness.memory_trials.procedural_bank",
    "ProceduralTaskRef": "harness.memory_trials.procedural_bank",
    "freeze_procedural_bank": "harness.memory_trials.procedural_bank",
    "seal_procedural_split_manifest": "harness.memory_trials.procedural_bank",
    "LONGMEMEVAL_ADAPTER_VERSION": "harness.memory_trials.public_sources",
    "LONGMEMEVAL_DATASET_ID": "harness.memory_trials.public_sources",
    "LONGMEMEVAL_DATASET_REVISION": "harness.memory_trials.public_sources",
    "LONGMEMEVAL_LICENSE": "harness.memory_trials.public_sources",
    "LONGMEMEVAL_QUESTION_TYPES": "harness.memory_trials.public_sources",
    "LONGMEMEVAL_SCREEN32_RAW_TASK_IDS": "harness.memory_trials.public_sources",
    "LONGMEMEVAL_TRANSPORT_PANEL_QUOTAS": "harness.memory_trials.public_sources",
    "LONGMEMEVAL_TRANSPORT_PANEL_SEED": "harness.memory_trials.public_sources",
    "LONGMEMEVAL_TRANSPORT_PANEL_VERSION": "harness.memory_trials.public_sources",
    "LONGMEMEVAL_FULL_TASK_MANIFEST_SHA256": "harness.memory_trials.public_sources",
    "LONGMEMEVAL_ORACLE_FILENAME": "harness.memory_trials.public_sources",
    "LONGMEMEVAL_ORACLE_ARTIFACT_ROLE": "harness.memory_trials.public_sources",
    "LONGMEMEVAL_ORACLE_SHA256": "harness.memory_trials.public_sources",
    "LONGMEMEVAL_ORACLE_SIZE": "harness.memory_trials.public_sources",
    "LONGMEMEVAL_OFFICIAL_EVALUATOR_SHA256": "harness.memory_trials.public_sources",
    "LONGMEMEVAL_REPOSITORY_REVISION": "harness.memory_trials.public_sources",
    "LONGMEMEVAL_RETRIEVAL_ADAPTER_VERSION": "harness.memory_trials.public_sources",
    "LONGMEMEVAL_RETRIEVAL_ARTIFACT_ROLE": "harness.memory_trials.public_sources",
    "LONGMEMEVAL_S_FILENAME": "harness.memory_trials.public_sources",
    "LONGMEMEVAL_S_SHA256": "harness.memory_trials.public_sources",
    "LONGMEMEVAL_S_SIZE": "harness.memory_trials.public_sources",
    "LONGMEMEVAL_SCREEN32_TASK_MANIFEST_SHA256": "harness.memory_trials.public_sources",
    "LongMemEvalTaskSource": "harness.memory_trials.public_sources",
    "PublicMemorySourceError": "harness.memory_trials.public_sources",
    "longmemeval_download_url": "harness.memory_trials.public_sources",
    "derive_longmemeval_transport_panel": "harness.memory_trials.public_sources",
    "QualityCollectionError": "harness.memory_trials.quality",
    "QualityCollectionResult": "harness.memory_trials.quality",
    "collect_all_serve": "harness.memory_trials.quality",
    "load_quality_outcomes": "harness.memory_trials.quality",
    "EventKind": "harness.memory_trials.schema",
    "MemoryBudget": "harness.memory_trials.schema",
    "MemoryEvent": "harness.memory_trials.schema",
    "MemoryOracle": "harness.memory_trials.schema",
    "MemoryRecord": "harness.memory_trials.schema",
    "MemoryStratum": "harness.memory_trials.schema",
    "MemoryTask": "harness.memory_trials.schema",
    "MemorySidecarError": "harness.memory_trials.sidecar",
    "PersistentSubprocessMemorySystem": "harness.memory_trials.sidecar",
    "SubprocessMemorySystem": "harness.memory_trials.sidecar",
    "GeneratedMemoryTaskSource": "harness.memory_trials.sources",
    "GeneratedSafetyMemoryTaskSource": "harness.memory_trials.sources",
    "GENERATED_MEMORY_VERSION": "harness.memory_trials.sources",
    "MemoryTaskSource": "harness.memory_trials.sources",
    "FamilySplittableTaskSource": "harness.memory_trials.splits",
    "SplitCounts": "harness.memory_trials.splits",
    "SplitManifestError": "harness.memory_trials.splits",
    "SplitName": "harness.memory_trials.splits",
    "TaskSplitEntry": "harness.memory_trials.splits",
    "TaskSplitManifest": "harness.memory_trials.splits",
    "make_exact_family_split": "harness.memory_trials.splits",
    "validate_split_manifest": "harness.memory_trials.splits",
    "FullPrefixCeilingSystem": "harness.memory_trials.systems",
    "LexicalMemorySystem": "harness.memory_trials.systems",
    "LRUMemorySystem": "harness.memory_trials.systems",
    "BM25MemorySystem": "harness.memory_trials.systems",
    "MemoryBankDecayMemorySystem": "harness.memory_trials.systems",
    "MemoryCostLedger": "harness.memory_trials.systems",
    "MemoryEvidence": "harness.memory_trials.systems",
    "MemorySelection": "harness.memory_trials.systems",
    "MemorySystemEvent": "harness.memory_trials.systems",
    "MemorySystemReceipt": "harness.memory_trials.systems",
    "MemorySystemRequest": "harness.memory_trials.systems",
    "MemorySystemRun": "harness.memory_trials.systems",
    "NoMemorySystem": "harness.memory_trials.systems",
    "ProfileExpansionMemorySystem": "harness.memory_trials.systems",
    "RawLogRRFMemorySystem": "harness.memory_trials.systems",
    "RecencyMemorySystem": "harness.memory_trials.systems",
    "ReferenceMemorySystem": "harness.memory_trials.systems",
    "TemporalGraphMemorySystem": "harness.memory_trials.systems",
    "build_memory_system_request": "harness.memory_trials.systems",
    "materialize_prefix_records": "harness.memory_trials.systems",
    "materialize_request_records": "harness.memory_trials.systems",
    "run_memory_system": "harness.memory_trials.systems",
}

__all__ = sorted(_EXPORTS)


def __getattr__(name: str) -> object:
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(importlib.import_module(module_name), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted({*globals(), *__all__})
